name: Build
on:
  push:
    branches:
      - vim

jobs:
  build-project:
    name: Build Project
    runs-on: macos-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: true
      - name: install deps
        run: |
          brew install llvm cmake

      - name: Build Project
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ledit_darwin_aarch64
          path: |
            build/ledit
